Convert/java to kotlin
gracenudze/money-manager pull request #3
Opened 2022-03-24 16:02 UTC by gracenudze

2022-03-24 18:05 UTC, James-Aidoo requested changes
Good job. 

However, Implement these suggestions.

2022-03-24 18:05 UTC, James-Aidoo commented on app/build.gradle
> +//}
remove commented code

2022-03-24 18:05 UTC, James-Aidoo commented on app/src/main/java/com/example/moneymanager/ActivityList.kt
> +class ActivityList(val activityIcons: Int, val activityNames: String, val activityDates: String, val balance: String)
There doesn't seem to be anything "Listy" about this class. Consider renaming it. Also, you should probably make it a data class

It is considered good practice to leave an empty line at the end of your files

2022-03-24 18:05 UTC, James-Aidoo commented on app/src/main/java/com/example/moneymanager/GamingRoomActivity.kt
> +    var activity_balance = arrayOf("-$54", "-$54", "-$54")
Follow naming convention: `activity_names` > `activityNames`, `activity_dates` > `activityDates`, `activity_balance` > `activityBalance`.

2022-03-24 18:05 UTC, James-Aidoo commented on app/src/main/java/com/example/moneymanager/GamingRoomActivity.kt
> +    var activityList = ArrayList<ActivityList>()
For all your mutable (`var`) variables, if you do not reassign new values to them anywhere later in your code, make them immutable (`val`).

2022-03-24 18:05 UTC, James-Aidoo commented on app/src/main/java/com/example/moneymanager/GamingRoomActivity.kt
> +}
It is considered good practice to leave an empty line at the end of your files

2022-03-24 18:05 UTC, James-Aidoo commented on app/src/main/java/com/example/moneymanager/GamingRoomAdapter.kt
> +}
It is considered good practice to leave an empty line at the end of your files

2022-03-24 18:05 UTC, James-Aidoo commented on app/src/main/java/com/example/moneymanager/MainActivity.kt
> +    var budget = arrayOf("-$54", "-$29")
For all your mutable (`var`) variables, if you do not reassign new values to them anywhere later in your code, make them immutable (`val`).

2022-03-24 18:05 UTC, James-Aidoo commented on app/src/main/java/com/example/moneymanager/MainActivity.kt
> +        for ((count, names) in transactionNames.withIndex()) {
`count` variable does not reflect what that value actually is. Consider using a more appropriate name like `index`.

2022-03-24 18:05 UTC, James-Aidoo commented on app/src/main/java/com/example/moneymanager/MainActivity.kt
> +}
It is considered good practice to leave an empty line at the end of your files

2022-03-24 18:05 UTC, James-Aidoo commented on app/src/main/java/com/example/moneymanager/TransactionAdapter.kt
> +}
It is considered good practice to leave an empty line at the end of your files

2022-03-24 18:05 UTC, James-Aidoo commented on app/src/main/java/com/example/moneymanager/TransactionList.kt
> +class TransactionList(val transactionLogos: Int, val transactionNames: String, val transactionDate: String, val budget: String)
There doesn't seem to be anything "Listy" about this class. Consider renaming it. Also, you should probably make it a data class.

It is considered good practice to leave an empty line at the end of your files

2022-03-24 18:05 UTC, James-Aidoo commented on build.gradle
> +//        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.5'
Remote commented code

2022-03-24 18:05 UTC, James-Aidoo commented on build.gradle
> +//repositories {
Remove commented code

It is considered good practice to leave an empty line at the end of your files

2022-03-25 10:34 UTC, gracenudze commented on app/src/main/java/com/example/moneymanager/ActivityList.kt
> +class ActivityList(val activityIcons: Int, val activityNames: String, val activityDates: String, val balance: String)
I named it list because it is part of the recyclerview list process

2022-03-25 10:38 UTC, James-Aidoo commented on app/src/main/java/com/example/moneymanager/ActivityList.kt
> +class ActivityList(val activityIcons: Int, val activityNames: String, val activityDates: String, val balance: String)
I get that. However, the class isn't a list. It having `list` in it's name conveys a different message than what it's purpose actually is.

2022-03-25 10:44 UTC, gracenudze commented on app/src/main/java/com/example/moneymanager/GamingRoomActivity.kt
> +    var activityList = ArrayList<ActivityList>()
okay

2022-03-25 13:07 UTC, James-Aidoo requested changes

2022-03-25 13:07 UTC, James-Aidoo commented on app/src/main/java/com/example/moneymanager/ActivityRecycler.kt
> +data class ActivityRecycler(val activityIcons: Int, val activityNames: String, val activityDates: String, val balance: String)
A more appropriate name would be `ActivityItem`, considering this class isn't  a `Recycler`View.

2022-03-25 13:07 UTC, James-Aidoo commented on app/src/main/java/com/example/moneymanager/GamingRoomActivity.kt
> +        for ((count, names) in activityNames.withIndex()) {
`index` would be more appropriate than `count`, don't you think?

2022-03-25 13:07 UTC, James-Aidoo commented on app/src/main/java/com/example/moneymanager/TransactionRecycler.kt
> +data class TransactionRecycler(val transactionLogos: Int, val transactionNames: String, val transactionDate: String, val budget: String)
`TransactionItem`

2022-03-25 13:53 UTC, James-Aidoo approved these changes

2022-03-25 14:23 UTC, merged