Refactoring and Enhancement of Code
gracenudze/money-manager pull request #6
Opened 2022-03-30 15:35 UTC by gracenudze

Refactoring the names of the variables, removing redundancies and enhancing the code

2022-03-31 14:26 UTC, James-Aidoo requested changes
Great work so far. Make these suggested changes and let's move on to the next issue

2022-03-31 14:26 UTC, James-Aidoo commented on app/src/main/java/com/example/moneymanager/GamingRoomActivity.kt
> +        val firstSection = GamingRoomAdapter(activities)
Consider renaming `firstSection` to something that reflects what it it is supposed be, like `activitiesAdapter`.
Better still, since you never use the adapter directly in your code, you could just assign the result of instantiating the adapter class to the `activityRecycler`s adapter property: 
`activityRecycler.adapter = GamingRoomAdapter(activities)`

2022-03-31 14:26 UTC, James-Aidoo commented on app/src/main/java/com/example/moneymanager/MainActivity.kt
>          transactionRecycler.adapter = firstSection
Merge these two: `transactionRecycler.adapter = TransactionAdapter(transactions)`

2022-03-31 14:26 UTC, James-Aidoo commented on app/src/main/java/com/example/moneymanager/MainActivity.kt
>          btnCreate!!.setOnClickListener {
It is safer (and advisable, I suppose) to use the null check operator `?` than the double bang `!!`, unless you're 100% sure that the receiver is not going to be null. Even then, you probably should play it safe and use the null check operator instead: Consider changing to the below, which uses the null check operator:

`btnCreate?.setOnClickListener {
    ...
}`

2022-04-01 08:37 UTC, James-Aidoo requested changes
Make this change

2022-04-01 08:37 UTC, James-Aidoo commented on app/src/main/java/com/example/moneymanager/GamingRoomActivity.kt
> +        activityRecycler.adapter = latestActivities
Join these two lines:
`activityRecycler.adapter = GamingRoomAdapter(activities)`

2022-04-01 08:53 UTC, gracenudze commented on app/src/main/java/com/example/moneymanager/GamingRoomActivity.kt
> +        activityRecycler.adapter = latestActivities
alright please

2022-04-01 09:52 UTC, James-Aidoo approved these changes
You're good to merge

2022-04-01 09:58 UTC, merged